services:
  nx-multi-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nx-multi-app
    ports:
      - '4200:80' # app-1
      - '4201:81' # app-2
    environment:
      - NODE_ENV=production
    restart: unless-stopped
